# Installation

[optionally] create a virtual environment with Python 3.10.15

In [60]:
!pip install -r requirements.txt

  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
  Using cached opencv_python-4.11.0.86-cp37-abi3-macosx_13_0_arm64.whl.metadata (20 kB)
  Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
  Using cached jinja2-3.1.5-py3-none-any.whl.metadata (2.6 kB)
  Using cached fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
  Using cached setuptools-75.8.0-py3-none-any.whl.metadata (6.7 kB)
  Using cached sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
  Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-a

# Download the dataset and model  
Please refer to the instructions in [README.md](./README.md).

# Run the code

## NeuMaDiff: Neural Material Synthesis via Hyperdiffusion

In [61]:
# output folder
!mkdir -p output/generation/

- Sample synthetic materials from the pre-trained hyperdiffusion [synthesis model weights](https://huggingface.co/Peter2023HuggingFace/M3ashy).

In [ ]:
!python src/pytorch/train.py --file_index -1  --pytorch_model_type 2 --sample 1 --model_weights_path model/NeuMaDiff-diversity.pth

Using following input parameter splits: [675, 257]
['mlp_weights', 'timestep_embedding']
number of parameters: 86,293,248
{
    "model": "HyperDiffusion",
    "use_cond": false,
    "cond_label": {
        "unconditional_guidance_scale": 0
    }
}
(2400, 675)
Train/Infer split with seed value: 0
Train size: 2280  Infer size: 120
/Users/peterhu/Documents/Coding/GitHub/Paper/NeuMaDiff/src/pytorch/model_factory.py:175: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless the

In [68]:
!python src/pytorch/train.py --file_index -1  --pytorch_model_type 2 --sample 1 --model_weights_path model/NeuMaDiff-quality.pth

Using following input parameter splits: [675, 257]
['mlp_weights', 'timestep_embedding']
number of parameters: 86,293,248
{
    "model": "HyperDiffusion",
    "use_cond": false,
    "cond_label": {
        "unconditional_guidance_scale": 0
    }
}
(2400, 675)
Train/Infer split with seed value: 0
Train size: 2280  Infer size: 120
/Users/peterhu/Documents/Coding/GitHub/Paper/NeuMaDiff/src/pytorch/model_factory.py:175: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless the

-  Create folders for the generated materials.

In [2]:
!mkdir -p output/generation/mlp/mlp_gen{0..120}

- Extract the MLP model from the npy file.

In [3]:
!python src/tools/merl_workflow/read_mlp_weight.py --file_index -1

Saved model: output/generation/mlp/mlp_gen0/model0.pth
Saved model: output/generation/mlp/mlp_gen1/model1.pth
Saved model: output/generation/mlp/mlp_gen2/model2.pth
Saved model: output/generation/mlp/mlp_gen3/model3.pth
Saved model: output/generation/mlp/mlp_gen4/model4.pth
Saved model: output/generation/mlp/mlp_gen5/model5.pth
Saved model: output/generation/mlp/mlp_gen6/model6.pth
Saved model: output/generation/mlp/mlp_gen7/model7.pth
Saved model: output/generation/mlp/mlp_gen8/model8.pth
Saved model: output/generation/mlp/mlp_gen9/model9.pth
Saved model: output/generation/mlp/mlp_gen10/model10.pth
Saved model: output/generation/mlp/mlp_gen11/model11.pth
Saved model: output/generation/mlp/mlp_gen12/model12.pth
Saved model: output/generation/mlp/mlp_gen13/model13.pth
Saved model: output/generation/mlp/mlp_gen14/model14.pth
Saved model: output/generation/mlp/mlp_gen15/model15.pth
Saved model: output/generation/mlp/mlp_gen16/model16.pth
Saved model: output/generation/mlp/mlp_gen17/model1

- Infer the binary files of the synthesized materials from the MLP model, following [MERL](https://www.merl.com/research/downloads/BRDF) format.

In [4]:
!python src/tools/merl_workflow/write_merl_binary.py --file_index -1

(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)
(4374000,)

- Rendering with the binary material to images.

We use [Mitsuba](https://www.mitsuba-renderer.org/), a physically based renderer, to render the 3D models with the synthesized materials.  You may find [Neural-BRDF](https://github.com/asztr/Neural-BRDF) helpful.


- [Optionally] Train a new hyperdiffusion model.

In [54]:
!python src/pytorch/train.py --file_index -1  --pytorch_model_type 2

Using following input parameter splits: [675, 257]
['mlp_weights', 'timestep_embedding']
number of parameters: 86,293,248
{
    "model": "HyperDiffusion",
    "use_cond": false,
    "cond_label": {
        "unconditional_guidance_scale": 0
    }
}
(2400, 675)
Train/Infer split with seed value: 0
Train size: 2280  Infer size: 120
Batch size:  16
Number of epochs:  1
Train epoch:1
Epoch number [1/1], train Loss:1.2302
Lr:5.00E-04


## Evaluation of synthesized materials

Please update the folder and filename to `.binary` files or render images of reference and synthesized sets.

There are two underlying distance metrics: BRDF space and image space. (For BRDF space, the demo use `data/merl/blue-metallic-paint.binary` from MERL dataset.)

- For BRDF space, the demo use `data/merl/blue-metallic-paint.binary` from MERL dataset.

In [55]:
# BRDF space
!python src/eval/metrics.py --is_brdf_space 1 --refer_set_size 1  --reference_folder_path "data/merl/" --sample_set_size 1  --sample_folder_path "data/merl/" 

Loading sample BRDF: 100%|████████████████████████| 1/1 [00:00<00:00,  6.06it/s]
Type: 1
Metrics: Log-cos-L1
Pairwise Distance: 100%|██████████████████████████| 1/1 [00:00<00:00,  4.17it/s]
Matched reference BRDF id indexed by sample BRDF:
tensor([0], device='mps:0')
Distance: 100%|███████████████████████████████████| 1/1 [00:00<00:00, 14.56it/s]
[minimum matching distance (from ref) (↓)]: 0.00000000
[coverage (↑)]: 1.00000000
[minimum matching distance (from sample)]: 0.00000000
[1-Nearest-Neighbour-acc_t (50%)]: 0.00000000
[1-Nearest-Neighbour-acc_f (50%)]: 0.00000000
[1-Nearest-Neighbour-acc (50%)]: 0.00000000
Type: 2
Metrics: Log-L1
Pairwise Distance: 100%|██████████████████████████| 1/1 [00:00<00:00, 24.12it/s]
Matched reference BRDF id indexed by sample BRDF:
tensor([0], device='mps:0')
Distance: 100%|███████████████████████████████████| 1/1 [00:00<00:00, 29.65it/s]
[minimum matching distance (from ref) (↓)]: 0.00000000
[coverage (↑)]: 1.00000000
[minimum matching distance (from 

- For BRDF space, the demo use `data/merl/blue-metallic-paint.binary` from MERL dataset.

In [56]:
# image space
!python src/eval/metrics.py --is_brdf_space 0 --refer_set_size 1 --reference_img_path "output/img/" --sample_set_size 1 --sample_img_path "output/img/"

Loading reference BRDF images: 100%|█████████████| 1/1 [00:00<00:00, 166.96it/s]
(1, 256, 256, 3)
Loading sample BRDF images: 100%|███████████████| 1/1 [00:00<00:00, 1102.89it/s]
(1, 256, 256, 3)
Type: 1
Metrics: SSIM
Pairwise Distance: 100%|██████████████████████████| 1/1 [00:00<00:00, 53.20it/s]
Matched reference BRDF id indexed by sample BRDF:
tensor([0])
Distance: 100%|██████████████████████████████████| 1/1 [00:00<00:00, 456.65it/s]
[minimum matching distance (from ref) (↓)]: -0.01197730
[coverage (↑)]: 1.00000000
[minimum matching distance (from sample)]: -0.01197730
[1-Nearest-Neighbour-acc_t (50%)]: 0.00000000
[1-Nearest-Neighbour-acc_f (50%)]: 0.00000000
[1-Nearest-Neighbour-acc (50%)]: 0.00000000
Type: 2
Metrics: PSNR
Pairwise Distance: 100%|██████████████████████████| 1/1 [00:00<00:00, 60.07it/s]
Matched reference BRDF id indexed by sample BRDF:
tensor([0])
Distance: 100%|██████████████████████████████████| 1/1 [00:00<00:00, 398.70it/s]
[minimum matching distance (from ref) 

## [Optional] NeuMERL: Training MLP from scratch

To train the NeuMERL from scratch, please download MERL dataset from [MERL](https://www.merl.com/research/downloads/BRDF) and put the binary files in the `data/merl` folder (see details [here](./data/merl/README.md)). Please download the [initial model weights](https://huggingface.co/datasets/Peter2023HuggingFace/NeuMERL/blob/main/mlp_weights_ini.pth) and put them in the `model` folder (see details [here](model/README.md)).

In [57]:
# output folder
!mkdir -p output/merl/merl_1/blue-metallic-paint/

- Train a NeuMERL MLP model from scratch.  

In [58]:
!python src/pytorch/train.py --pytorch_model_type 1  --file_index 1  

1 blue-metallic-paint
Batch size:  512
Number of epochs:  1
/Users/peterhu/Documents/Coding/GitHub/Paper/NeuMaDiff/src/pytorch/model_factory.py:175: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this ex

See more details in the [README.md](./README.md).